# Generated by Django 4.1.7 on 2023-03-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250, unique=True)),
                ('ch_min', models.CharField(max_length=250)),
                ('ch_max', models.CharField(max_length=250)),
                ('ap_max', models.CharField(max_length=250)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidade.modalidade')),
            ],
        ),
    ]
