# Generated by Django 4.1.7 on 2023-03-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aproveitamento',
            fields=[
                ('id_aproveitamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=50)),
                ('ch', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.atividade')),
            ],
        ),
    ]
